#include "arduino_secrets.h"

 /*
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/ad5cb7c6-e0e0-4f98-af8e-51a5fd9c8020

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudSwitch heat_fan;
  CloudTemperatureSensor tempC;
  CloudTemperatureSensor tempF;
  int servo;
  CloudRelativeHumidity humi;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/





#include "thingProperties.h"


void setup() {
 
  /

}

void loop() {

 
  
}


/*
  Since Temperature is READ_WRITE variable, onTemperatureChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onTemperatureChange()  {
 
  // Add your code here to act upon Temperature change
}

void DHT_SENSOR_READ()
{// read humidity
   
   

  // check if any reads failed
  
 
}
/*
  Since Servo is READ_WRITE variable, onServoChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onServoChange()  {

}

/*
  Since HeatFan is READ_WRITE variable, onHeatFanChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onHeatFanChange()  {
   
}

