// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "5d5e561f-2da5-4188-a0c6-d3a9aee9a0b7";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onHeatFanChange();
void onServoChange();

CloudSwitch heat_fan;
CloudTemperatureSensor tempC;
CloudTemperatureSensor tempF;
int servo;
CloudRelativeHumidity humi;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(heat_fan, READWRITE, ON_CHANGE, onHeatFanChange);
  ArduinoCloud.addProperty(tempC, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(tempF, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(servo, READWRITE, ON_CHANGE, onServoChange, 90);
  ArduinoCloud.addProperty(humi, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
